server:
  port: 8081
  


endpoints:
  default:
    web:
      enabled: true

info: 
  app:
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@


#spring:
#  zipkin:
#    baseUrl:  http://localhost:9411

#security:
#  oauth2:
#   resource:
#      userInfoUri: http://localhost:8080/user
      
logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.tianyalan: INFO

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

        