spring:
  jpa:
    database: MYSQL
  datasource:
    platform: mysql
    url: jdbc:mysql://192.168.0.103:3306/microservice_account
    username: root
    password: "{cipher}9fb93b6220467130f200ae312d98237c8c2aa055de5e5e3f858da1eb86a3f289"
    driver-class-name: com.mysql.jdbc.Driver